[package]
name        = "prune-juice-cli"
description = "Prune Juice command-line interface"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true

[[bin]]
name = "prune-juice"
path = "src/main.rs"

[dependencies]
prune-juice-core = { path = "../prune-juice-core" }
prune-juice-tui  = { path = "../prune-juice-tui" }
serde_json.workspace = true
