//! Content probing.
//!
//! Labels answer *whose is it*. Only the contents answer *what is it* — and
//! that distinction is what stands between "unreferenced anonymous volume" and
//! "the only copy of a client's database". A `docker run postgres` with no `-v`
//! produces a volume that is unreferenced, unlabelled, and full of data.
//!
//! Two strategies, both strictly read-only:
//!
//! * **Native** — read the daemon's data root directly. OrbStack NFS-mounts it
//!   at `~/OrbStack/docker/volumes`, and a native Linux daemon exposes
//!   `<DockerRootDir>/volumes/<name>/_data`. No container, no state change,
//!   259 volumes in well under a second on the reference machine.
//! * **Container** — mount read-only into a throwaway container. Needed on
//!   Docker Desktop, which hides its data root inside a VM. Not implemented
//!   yet; [`VolumeAccess::resolve`] returns `None` and the caller reports the
//!   volume as unprobed rather than guessing.
//!
//! Nothing here writes. A probe must never be the reason a volume changes.

use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};

use crate::model::{Bytes, RuntimeFlavor};

/// Stop walking after this many entries. A `node_modules` can hold hundreds of
/// thousands of files and we only need enough to classify it.
const WALK_LIMIT: usize = 20_000;

/// What a volume turns out to contain.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case", tag = "class", content = "detail")]
pub enum ContentClass {
    /// Nothing at all. Trivially reconstructible: there is nothing to lose.
    Empty,
    /// A cache or dependency tree that a build regenerates.
    Derivative(String),
    /// A database data directory. Precious unless proven otherwise.
    Database(Engine),
    /// Files that look like something a person put there — uploads, media.
    UserData,
    /// Readable, but nothing recognised. Treated as precious.
    Unrecognised,
}

impl ContentClass {
    /// Can this be thrown away and recreated from something that survives?
    ///
    /// Only two answers qualify, and neither involves guessing about a
    /// database.
    pub fn is_reconstructible(&self) -> bool {
        matches!(self, ContentClass::Empty | ContentClass::Derivative(_))
    }

    pub fn describe(&self) -> String {
        match self {
            ContentClass::Empty => "empty".into(),
            ContentClass::Derivative(what) => format!("{what} — regenerated by a build"),
            ContentClass::Database(e) => format!("{} data directory", e.as_str()),
            ContentClass::UserData => "user data".into(),
            ContentClass::Unrecognised => "contents not recognised".into(),
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Engine {
    Postgres,
    MySql,
    MariaDb,
    Mongo,
    Redis,
    Elasticsearch,
}

impl Engine {
    pub fn as_str(self) -> &'static str {
        match self {
            Engine::Postgres => "PostgreSQL",
            Engine::MySql => "MySQL",
            Engine::MariaDb => "MariaDB",
            Engine::Mongo => "MongoDB",
            Engine::Redis => "Redis",
            Engine::Elasticsearch => "Elasticsearch",
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ProbeMethod {
    /// Read straight off the host filesystem. No container involved.
    Native,
    /// A throwaway read-only container. Not yet implemented.
    Container,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ContentReport {
    pub class: ContentClass,
    pub method: ProbeMethod,
    /// Top-level entries, capped for display.
    pub entries: Vec<String>,
    /// Non-directory objects seen. A floor, not a total, whenever
    /// [`Self::truncated`] is set — and `0` with `truncated` set means nobody
    /// counted, which is not the same fact as "there are none".
    pub file_count: u64,
    /// True when the walk stopped early — its depth cap, its entry cap, or a
    /// counter that never ran — so counts are a floor.
    pub truncated: bool,
    pub bytes: Bytes,
    /// Newest mtime anywhere in the volume, unix seconds.
    ///
    /// The strongest "precious" signal there is: bytes newer than the owning
    /// project's last commit mean work that exists nowhere else.
    pub newest_mtime: Option<i64>,
}

impl ContentReport {
    /// One citable line, for the evidence list a human reads.
    pub fn summary(&self) -> String {
        if self.entries.is_empty() {
            return self.class.describe();
        }
        let shown: Vec<&str> = self.entries.iter().take(4).map(String::as_str).collect();
        format!("{} — {}", self.class.describe(), shown.join(", "))
    }
}

/// Where a volume's bytes live on the host, when they are reachable at all.
pub struct VolumeAccess {
    root: Option<PathBuf>,
    /// Native Linux nests the payload under `_data`; OrbStack's NFS view does
    /// not.
    nested_data: bool,
}

impl VolumeAccess {
    /// Work out whether this daemon's volumes can be read directly.
    pub fn detect(runtime: RuntimeFlavor, data_root: Option<&str>) -> Self {
        if runtime == RuntimeFlavor::OrbStack {
            if let Ok(home) = std::env::var("HOME") {
                let p = PathBuf::from(home).join("OrbStack/docker/volumes");
                if p.is_dir() {
                    return Self {
                        root: Some(p),
                        nested_data: false,
                    };
                }
            }
        }

        // A native Linux daemon's data root is a real host path. Inside a VM
        // the same string exists only in the guest, so it must be checked
        // rather than trusted.
        if runtime == RuntimeFlavor::NativeLinux {
            if let Some(dr) = data_root {
                let p = PathBuf::from(dr).join("volumes");
                if p.is_dir() {
                    return Self {
                        root: Some(p),
                        nested_data: true,
                    };
                }
            }
        }

        Self {
            root: None,
            nested_data: false,
        }
    }

    pub fn is_available(&self) -> bool {
        self.root.is_some()
    }

    /// Path to a volume's contents, if reachable.
    pub fn resolve(&self, volume: &str) -> Option<PathBuf> {
        // Volume names come from the daemon, but they still reach a filesystem
        // API, so anything that could climb out of the root is refused.
        if volume.is_empty()
            || volume.contains('/')
            || volume.contains('\\')
            || volume.contains("..")
        {
            return None;
        }
        let root = self.root.as_ref()?;
        let p = if self.nested_data {
            root.join(volume).join("_data")
        } else {
            root.join(volume)
        };
        p.is_dir().then_some(p)
    }

    /// Probe one volume. Returns `None` when its bytes are not reachable —
    /// which is reported as "not probed", never assumed to mean empty.
    pub fn probe(&self, volume: &str) -> Option<ContentReport> {
        let path = self.resolve(volume)?;
        Some(probe_dir(&path))
    }

    /// The cheap probe used during a scan.
    ///
    /// Classification only needs the top-level layout, and a shallow walk over
    /// 259 volumes costs milliseconds where a full one would walk 35 GB. The
    /// resulting counts are a floor and `truncated` says so.
    ///
    /// This is sound for the only two classes that unlock deletion: `Empty` is
    /// definitive from the top level, and `Derivative` is reconstructible by
    /// definition, so neither depends on an exact byte count.
    pub fn probe_shallow(&self, volume: &str) -> Option<ContentReport> {
        let path = self.resolve(volume)?;
        Some(probe_dir_to_depth(&path, 2))
    }
}

/// Turn a container probe's raw output into a report.
///
/// Deliberately shares `classify` with the native path, so a volume is judged
/// by the same rules however its bytes were read. The only difference is
/// honesty about precision: container counts are capped and the mtime is
/// sampled, so `truncated` is set.
pub fn from_raw(raw: &crate::docker::RawProbe) -> ContentReport {
    ContentReport {
        // `None` is a probe image whose shell had no `find`: the script listed
        // the top level and counted nothing. Passed through as "uncounted", so
        // a volume nobody could count is never read as a volume holding
        // nothing.
        class: classify(&raw.entries, raw.file_count),
        method: ProbeMethod::Container,
        entries: raw.entries.clone(),
        file_count: raw.file_count.unwrap_or(0),
        truncated: raw.mtime_sampled || raw.file_count.is_none(),
        // The daemon already told us the size; a probe container should not
        // walk 35 GB to recompute it.
        bytes: Bytes(0),
        newest_mtime: raw.newest_mtime,
    }
}

/// Classify a directory, walking it fully (to the standard depth cap).
pub fn probe_dir(path: &Path) -> ContentReport {
    probe_dir_to_depth(path, 12)
}

/// Classify a directory, descending at most `max_depth` levels.
pub fn probe_dir_to_depth(path: &Path, max_depth: u32) -> ContentReport {
    let mut entries: Vec<String> = Vec::new();
    // A directory we could not open lists as empty, which is the one reading
    // of "no entries" that must never reach `Empty`.
    let listed = std::fs::read_dir(path);
    let readable = listed.is_ok();
    if let Ok(rd) = listed {
        for e in rd.flatten() {
            entries.push(e.file_name().to_string_lossy().into_owned());
            if entries.len() >= 256 {
                break;
            }
        }
    }
    entries.sort();

    let mut walk = Walk {
        max_depth,
        ..Default::default()
    };
    walk.run(path, 0);

    // A truncated walk counted part of a tree, so its zero is "I did not
    // look", never "there is nothing there". The scan walks only two levels
    // deep, and a volume whose files all sit below that — `uploads/2024/01/`,
    // say — counts none of them.
    let class = classify(&entries, (readable && !walk.truncated).then_some(walk.objects));

    ContentReport {
        class,
        method: ProbeMethod::Native,
        entries,
        file_count: walk.objects,
        truncated: walk.truncated,
        bytes: Bytes(walk.bytes),
        newest_mtime: walk.newest,
    }
}

#[derive(Default)]
struct Walk {
    /// Non-directory objects seen — files and symlinks alike. A link is not
    /// followed, but it is still something that exists only here, so a volume
    /// holding nothing but links is not an empty one.
    objects: u64,
    bytes: u64,
    newest: Option<i64>,
    truncated: bool,
    visited: usize,
    max_depth: u32,
}

impl Walk {
    fn run(&mut self, dir: &Path, depth: u32) {
        // Depth cap as well as an entry cap: a pathological tree should slow us
        // down at most once.
        if depth >= self.max_depth || self.truncated {
            self.truncated |= depth >= self.max_depth;
            return;
        }
        let Ok(rd) = std::fs::read_dir(dir) else {
            return;
        };
        for entry in rd.flatten() {
            if self.visited >= WALK_LIMIT {
                self.truncated = true;
                return;
            }
            self.visited += 1;

            // `symlink_metadata` so a link into the wider filesystem is counted
            // as a link, never followed out of the volume.
            let Ok(md) = entry.metadata() else { continue };
            if md.is_symlink() {
                // Counted, never followed: walking it could report someone's
                // home directory as volume contents, but pretending it is not
                // there is how a volume of links reads as empty.
                self.objects += 1;
                continue;
            }
            if md.is_dir() {
                self.run(&entry.path(), depth + 1);
            } else {
                self.objects += 1;
                self.bytes = self.bytes.saturating_add(md.len());
                if let Ok(m) = md.modified() {
                    if let Ok(d) = m.duration_since(std::time::UNIX_EPOCH) {
                        let secs = d.as_secs() as i64;
                        self.newest = Some(self.newest.map_or(secs, |n: i64| n.max(secs)));
                    }
                }
            }
        }
    }
}

/// Match top-level entries against known layouts.
///
/// Order matters: a database signature must win over anything else, because
/// misreading a data directory as a cache is the failure that loses data.
///
/// `objects` is `Some(n)` only when the whole tree was walked and `n` is
/// therefore the true number of things in it. `None` means the count is a
/// floor taken from an incomplete walk — and a floor of zero proves nothing,
/// so it must never resolve to [`ContentClass::Empty`].
fn classify(entries: &[String], objects: Option<u64>) -> ContentClass {
    if entries.is_empty() {
        // An empty listing is only evidence of emptiness when the listing
        // actually happened and the walk agrees. A directory that could not be
        // opened, or one whose objects were never counted, lists exactly the
        // same way.
        return match objects {
            Some(0) => ContentClass::Empty,
            _ => ContentClass::Unrecognised,
        };
    }
    let has = |n: &str| entries.iter().any(|e| e == n);
    let any_starting = |p: &str| entries.iter().any(|e| e.starts_with(p));

    if has("PG_VERSION") || (has("base") && has("pg_wal")) || (has("base") && has("pg_xlog")) {
        return ContentClass::Database(Engine::Postgres);
    }
    // MariaDB ships aria logs; MySQL does not. Both have mysql/ and ibdata1.
    if any_starting("aria_log") || has("aria_log_control") {
        return ContentClass::Database(Engine::MariaDb);
    }
    if has("ibdata1") || any_starting("ib_logfile") || (has("mysql") && has("performance_schema")) {
        return ContentClass::Database(Engine::MySql);
    }
    if has("WiredTiger") || has("mongod.lock") {
        return ContentClass::Database(Engine::Mongo);
    }
    if has("dump.rdb") || has("appendonlydir") || has("appendonly.aof") {
        return ContentClass::Database(Engine::Redis);
    }
    if has("nodes") || has("_state") {
        return ContentClass::Database(Engine::Elasticsearch);
    }

    // A derivative marker only counts when it *dominates*. A volume whose top
    // level is `node_modules` is a dependency cache; a volume containing
    // `vendor` alongside `composer.json`, `wp-cli.yml` and `html/` is an entire
    // application checkout that merely happens to have vendored deps in it.
    //
    // This distinction is not academic. Treating the second as derivative
    // marked five volumes on the reference machine as safe to delete, two of
    // them 1.2 GB WordPress installations.
    const DERIVATIVE: [(&str, &str); 6] = [
        ("node_modules", "node_modules"),
        ("vendor", "composer vendor tree"),
        ("registry", "package registry cache"),
        (".cache", "cache directory"),
        ("_cacache", "npm cache"),
        ("cache", "cache directory"),
    ];
    // Entries that say nothing about what a volume is for.
    let is_noise = |e: &String| {
        e == "lost+found"
            || e == ".DS_Store"
            || e.starts_with(".fuse_hidden")
            || e == ".keep"
            || e == ".gitkeep"
    };
    let meaningful: Vec<&String> = entries.iter().filter(|e| !is_noise(e)).collect();
    if let Some((_, label)) = DERIVATIVE
        .iter()
        .find(|(name, _)| meaningful.len() == 1 && meaningful[0] == name)
    {
        return ContentClass::Derivative(label.to_string());
    }

    // A minio/S3 bucket layout: a few directories of user-uploaded objects.
    if has(".minio.sys") {
        return ContentClass::UserData;
    }

    if objects == Some(0) {
        // Directories, walked to the bottom, and not one file under any of
        // them. Nothing to lose.
        return ContentClass::Empty;
    }

    // Either something is here, or nobody could count what is. Both are
    // reasons to leave it alone: `Unknown` is not a soft `No`.
    ContentClass::Unrecognised
}

#[cfg(test)]
mod tests {
    use super::*;

    fn tmp(tag: &str) -> PathBuf {
        let d = std::env::temp_dir().join(format!(
            "pj-probe-{tag}-{}",
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        std::fs::create_dir_all(&d).unwrap();
        d
    }

    fn touch(dir: &Path, name: &str) {
        std::fs::write(dir.join(name), b"x").unwrap();
    }
    fn mkdir(dir: &Path, name: &str) -> PathBuf {
        let p = dir.join(name);
        std::fs::create_dir_all(&p).unwrap();
        p
    }

    #[test]
    fn an_empty_directory_is_empty() {
        let d = tmp("empty");
        let r = probe_dir(&d);
        assert_eq!(r.class, ContentClass::Empty);
        assert!(r.class.is_reconstructible());
        std::fs::remove_dir_all(&d).ok();
    }

    #[test]
    fn a_postgres_data_directory_is_recognised() {
        let d = tmp("pg");
        touch(&d, "PG_VERSION");
        mkdir(&d, "base");
        mkdir(&d, "pg_wal");
        let r = probe_dir(&d);
        assert_eq!(r.class, ContentClass::Database(Engine::Postgres));
        assert!(
            !r.class.is_reconstructible(),
            "a database must never read as reconstructible"
        );
        std::fs::remove_dir_all(&d).ok();
    }

    #[test]
    fn mariadb_is_distinguished_from_mysql() {
        let d = tmp("maria");
        touch(&d, "aria_log.00000001");
        touch(&d, "ibdata1");
        mkdir(&d, "mysql");
        assert_eq!(
            probe_dir(&d).class,
            ContentClass::Database(Engine::MariaDb),
            "aria logs mean MariaDB"
        );
        std::fs::remove_dir_all(&d).ok();

        let d = tmp("mysql");
        touch(&d, "ibdata1");
        mkdir(&d, "mysql");
        mkdir(&d, "performance_schema");
        assert_eq!(probe_dir(&d).class, ContentClass::Database(Engine::MySql));
        std::fs::remove_dir_all(&d).ok();
    }

    #[test]
    fn a_database_signature_beats_a_cache_signature() {
        // The dangerous confusion: a data directory that happens to contain a
        // directory called `cache` must not read as a throwaway cache.
        let d = tmp("both");
        touch(&d, "PG_VERSION");
        mkdir(&d, "cache");
        mkdir(&d, "node_modules");
        assert_eq!(
            probe_dir(&d).class,
            ContentClass::Database(Engine::Postgres)
        );
        std::fs::remove_dir_all(&d).ok();
    }

    #[test]
    fn a_volume_that_is_only_a_dependency_tree_is_derivative() {
        let d = tmp("deriv");
        mkdir(&d, "node_modules");
        touch(&d, "lost+found"); // noise must not defeat the match
        let r = probe_dir(&d);
        assert!(matches!(r.class, ContentClass::Derivative(_)));
        assert!(r.class.is_reconstructible());
        std::fs::remove_dir_all(&d).ok();
    }

    #[test]
    fn an_application_checkout_is_not_a_cache() {
        // The bug this guards: five volumes on the reference machine held whole
        // WordPress installations — html/, wp-cli.yml, composer.json — and
        // happened to contain `vendor`. Matching a derivative marker anywhere
        // in the listing marked 1.2 GB checkouts as safe to delete.
        let d = tmp("app");
        mkdir(&d, "html");
        mkdir(&d, "vendor");
        mkdir(&d, "web");
        touch(&d, "composer.json");
        touch(&d, "wp-cli.yml");
        let r = probe_dir(&d);
        assert_eq!(
            r.class,
            ContentClass::Unrecognised,
            "entries: {:?}",
            r.entries
        );
        assert!(
            !r.class.is_reconstructible(),
            "an application checkout must never read as reconstructible"
        );
        std::fs::remove_dir_all(&d).ok();
    }

    #[test]
    fn a_dependency_tree_beside_source_is_not_derivative() {
        let d = tmp("mixed");
        mkdir(&d, "node_modules");
        mkdir(&d, "src");
        touch(&d, "package.json");
        assert_eq!(probe_dir(&d).class, ContentClass::Unrecognised);
        std::fs::remove_dir_all(&d).ok();
    }

    #[test]
    fn unrecognised_contents_are_not_reconstructible() {
        let d = tmp("unknown");
        touch(&d, "something-odd.dat");
        let r = probe_dir(&d);
        assert_eq!(r.class, ContentClass::Unrecognised);
        assert!(
            !r.class.is_reconstructible(),
            "not recognising something is not a reason to delete it"
        );
        std::fs::remove_dir_all(&d).ok();
    }

    #[test]
    fn the_walk_records_size_and_newest_mtime() {
        let d = tmp("walk");
        touch(&d, "a");
        let sub = mkdir(&d, "sub");
        touch(&sub, "b");
        let r = probe_dir(&d);
        assert_eq!(r.file_count, 2);
        assert!(r.bytes.get() >= 2);
        assert!(r.newest_mtime.is_some());
        std::fs::remove_dir_all(&d).ok();
    }

    #[test]
    fn symlinks_are_counted_but_never_followed_out_of_the_volume() {
        // Two rules at once. A link pointing at the wider filesystem must not
        // be walked, or a probe could report someone's home directory as
        // volume contents. But it must still be *counted*: a link is a thing
        // that exists only here, and skipping it entirely is how a volume
        // holding nothing but links reads as empty and reaches Tier 1.
        let d = tmp("link");
        touch(&d, "real");
        #[cfg(unix)]
        std::os::unix::fs::symlink("/etc", d.join("escape")).unwrap();
        let r = probe_dir(&d);
        #[cfg(unix)]
        assert_eq!(r.file_count, 2, "the link counts as one object");
        assert!(
            r.bytes.get() < 10_000,
            "nothing behind the link may be measured, only the file in the volume"
        );
        std::fs::remove_dir_all(&d).ok();
    }

    #[cfg(unix)]
    #[test]
    fn a_volume_of_nothing_but_symlinks_is_not_empty() {
        let d = tmp("links-only");
        std::os::unix::fs::symlink("/etc/hosts", d.join("a")).unwrap();
        let r = probe_dir(&d);
        assert_ne!(r.class, ContentClass::Empty);
        assert!(!r.class.is_reconstructible());
        std::fs::remove_dir_all(&d).ok();
    }

    #[test]
    fn deep_contents_are_not_mistaken_for_an_empty_volume() {
        // The regression. The scan walks two levels; a volume of uploads is
        // `uploads/2024/01/photo.jpg`, so not one of its files is reached and
        // the count comes back zero. Reading that zero as "empty" put a
        // volume of someone's uploads in the tier that deletes with no
        // confirmation and no vault copy. A count nobody could take is not a
        // count of nothing.
        let d = tmp("deep");
        let year = mkdir(&mkdir(&d, "uploads"), "2024");
        touch(&mkdir(&year, "01"), "photo.jpg");

        let r = probe_dir_to_depth(&d, 2);
        assert!(r.truncated, "the walk did stop short");
        assert_eq!(r.file_count, 0, "and so counted nothing");
        assert_eq!(
            r.class,
            ContentClass::Unrecognised,
            "which must never read as empty"
        );
        assert!(!r.class.is_reconstructible());

        // The same tree, walked to the bottom, is recognisably not empty.
        assert_eq!(probe_dir(&d).class, ContentClass::Unrecognised);
        std::fs::remove_dir_all(&d).ok();
    }

    #[test]
    fn a_walk_that_reached_the_bottom_still_reports_empty() {
        // The other half of the fix: emptiness that was actually proven must
        // survive it, or the tool stops reclaiming the volumes it exists to
        // reclaim. `ivy-mariadb` on the reference machine is exactly this —
        // directories ddev created and never filled.
        let d = tmp("hollow");
        mkdir(&mkdir(&d, "a"), "b");
        let r = probe_dir_to_depth(&d, 12);
        assert!(!r.truncated);
        assert_eq!(r.class, ContentClass::Empty);
        assert!(r.class.is_reconstructible());
        std::fs::remove_dir_all(&d).ok();

        // And a volume with nothing in it at all, which is the commonest case.
        let d = tmp("bare");
        assert_eq!(probe_dir(&d).class, ContentClass::Empty);
        std::fs::remove_dir_all(&d).ok();
    }

    #[cfg(unix)]
    #[test]
    fn a_directory_that_cannot_be_read_is_not_an_empty_one() {
        use std::os::unix::fs::PermissionsExt;
        let d = tmp("locked");
        touch(&d, "secret");
        std::fs::set_permissions(&d, std::fs::Permissions::from_mode(0o000)).unwrap();
        let unreadable = std::fs::read_dir(&d).is_err();
        let r = probe_dir(&d);
        std::fs::set_permissions(&d, std::fs::Permissions::from_mode(0o755)).ok();
        std::fs::remove_dir_all(&d).ok();

        if unreadable {
            // Running as root reads it anyway, and then there is nothing to
            // assert; everywhere else, a listing that failed lists the same as
            // an empty directory and must not be read as one.
            assert_eq!(r.class, ContentClass::Unrecognised);
        }
    }

    #[test]
    fn a_probe_that_counted_nothing_is_not_a_probe_that_found_nothing() {
        // The container path, where the count comes from `find` inside the
        // probe image. An image whose shell has no `find` emits no count line
        // at all, and `None` must not collapse to zero.
        let uncounted = crate::docker::RawProbe {
            entries: vec!["uploads".into()],
            file_count: None,
            newest_mtime: None,
            mtime_sampled: true,
        };
        let r = from_raw(&uncounted);
        assert_eq!(r.class, ContentClass::Unrecognised);
        assert!(r.truncated, "an uncounted probe must admit it");

        // A volume the script really did look at and find nothing in.
        let empty = crate::docker::RawProbe {
            entries: vec![],
            file_count: Some(0),
            newest_mtime: None,
            mtime_sampled: true,
        };
        assert_eq!(from_raw(&empty).class, ContentClass::Empty);
    }

    #[test]
    fn a_shallow_walk_still_recognises_the_layout() {
        // The scan uses depth 2. Classification must not depend on descending
        // into a database's data files.
        let d = tmp("shallow");
        touch(&d, "PG_VERSION");
        let base = mkdir(&d, "base");
        let deep = mkdir(&base, "16384");
        touch(&deep, "2601");
        let r = probe_dir_to_depth(&d, 2);
        assert_eq!(r.class, ContentClass::Database(Engine::Postgres));
        assert!(
            r.truncated,
            "a capped walk must admit its counts are a floor"
        );
        std::fs::remove_dir_all(&d).ok();
    }

    #[test]
    fn empty_is_definitive_even_shallow() {
        // The class that unlocks deletion must be decidable without descending.
        let d = tmp("shallow-empty");
        assert_eq!(probe_dir_to_depth(&d, 2).class, ContentClass::Empty);
        std::fs::remove_dir_all(&d).ok();
    }

    #[test]
    fn resolve_refuses_a_traversing_name() {
        let d = tmp("resolve");
        let access = VolumeAccess {
            root: Some(d.clone()),
            nested_data: false,
        };
        mkdir(&d, "good");
        assert!(access.resolve("good").is_some());
        for bad in ["..", "../etc", "a/b", "", "a\\b"] {
            assert!(access.resolve(bad).is_none(), "must refuse {bad:?}");
        }
        std::fs::remove_dir_all(&d).ok();
    }

    #[test]
    fn unreachable_volumes_probe_to_none_rather_than_empty() {
        // Docker Desktop hides its data root. Reporting "not probed" is
        // correct; reporting "empty" would licence a deletion.
        let access = VolumeAccess {
            root: None,
            nested_data: false,
        };
        assert!(!access.is_available());
        assert!(access.probe("anything").is_none());
    }

    #[test]
    fn detect_returns_unavailable_for_a_vm_backed_runtime() {
        // Docker Desktop's DockerRootDir exists in the guest, not on the host.
        let a = VolumeAccess::detect(RuntimeFlavor::DockerDesktopMac, Some("/var/lib/docker"));
        assert!(!a.is_available());
    }
}
